language: go
go: 
 - 1.3.3
 - 1.4.2
 - 1.5.1
 - 1.7
 - 1.9
install:
  - go get -t ./...
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - PATH="$HOME/gopath/bin:$PATH"
  - script/coverage --coveralls